she_codes_news/news/urls.py
# news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('<int:pk>/update/', views.UpdateStoryView.as_view(), name='update_story'),
    path('<int:pk>/delete/', views.DeleteStoryView.as_view(), name='delete_story'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, UserProfileView
from . import views

app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('<int:pk>/user-profile/', UserProfileView.as_view(), name='user-profile'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    image = models.URLField(max_length=200, null=True, blank=True) #Add a new field to have images
    pub_date = models.DateTimeField(auto_now=True)  # Set auto_now=True for automatic date and time
    content = models.TextField()

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    #Extending user model to include bio
    bio = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

class StoryForm(ModelForm):
    class Meta: 
        model = NewsStory
        fields = ['title','image', 'content']

    # Add calendar input to set publish date
        # widgets = {
        #     'pub_date': forms.DateInput(
        #             format='%m/%d/%Y',
        #             attrs={
        #                 'class':'form-control',
        #                 'placeholder':'Select a date',
        #                 'type':'date'
        #             }
        #         ),
        #     }
        
        # Set required fields when updating and adding story
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            if self.instance.pk:
                self.fields['title'].required = True
                self.fields['content'].required = True
            else:
                # For DeleteStoryView, make fields not required
                self.fields['title'].required = False
                self.fields['content'].required = False

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email','first_name','last_name']

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email','first_name','last_name', 'bio']

she_codes_news/news/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm
from django.db.models import Q


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Get search query from the request's GET parameters '''
        search_query = self.request.GET.get('search')

        ''' If search is present, filter queryset by author'''
        if search_query:
            queryset = NewsStory.objects.filter(Q(author__username__icontains=search_query) | Q(content__icontains=search_query))
        else:
            '''Display all stories'''
            queryset = NewsStory.objects.all()
        '''Return all news stories.'''
    
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    Context_object_name = 'story'

class StoryView(generic.DeleteView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name='story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyform'
    template_name = 'news/createStory.html'
    success_url = reverse_lazy('news:index')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class UpdateStoryView(generic.UpdateView):
    model = NewsStory
    form_class = StoryForm
    template_name = 'news/updateStory.html'
    context_object_name = 'story'
    success_url = reverse_lazy('news:index')

class DeleteStoryView(generic.DeleteView):
    model = NewsStory
    template_name = 'news/updateStory.html' #use same template as Update view
    context_object_name='story'
    success_url = reverse_lazy('news:index') #redirect to index page upon successful deletion

    def get(self, request, *args, **kwargs):
        #handle GET request to display the confirmation dialog
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        #handle POST request to delete the story
        return super().post(request, *args, **kwargs)

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView
from .models import CustomUser
from .forms import CustomUserCreationForm, CustomUserChangeForm

class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login') # The `reverse_lazy` function is used to provide the success URL as a string
    template_name = 'users/createAccount.html'

class UserProfileView(DetailView, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'users/user-profile.html'
    success_url = reverse_lazy('news:index') #Could not get redirect to user profile to work, so using index for now.

    def get_object(self, queryset=None):
        # Use the captured 'pk' from the URL to fetch the specific user's profile
        return self.model.objects.get(pk=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.get_form()
        return context

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="POST IT">
    </form>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="search">
        <h2>All Stories</h2>
        <!-- Add the search form -->
        <form method="GET">
            <input type="text" name="search" placeholder="Search by author">
            <button type="submit">Search</button>
            {% comment %} Add refresh button to clear search and display all stories {% endcomment %}
            <a href="{% url 'news:index' %}" class="btn btn-secondary">Refresh</a> 
        </form>
        
    </div>
    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock %}

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}">
{% endblock %}

{% block content %}

    {% comment %} Allow authenticated user to edit story {% endcomment %}
    {% if user.is_authenticated %}
    <a href="{% url 'news:update_story' story.id %}">Edit</a>
    {% endif %}

    <div id="story-wrapper">
        <h2>{{ story.title }}</h2>
        <h4>{{ story.author }}</h4>
        
        <div id="story-content">
            {% if story.image is not None %}
                <img src =" {{ story.image }} ">
            {% else %}
                <img src="https://picsum.photos/id/1/600">
            {% endif %}
            {{ story.content|linebreaks }}
        </div>
    </div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
{% load static %}

<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if story.image is not None %}
            <img src =" {{ story.image }} ">
            {% else %}
            <img src="https://picsum.photos/id/1/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/updateStory.html
{% extends 'base.html' %}

{% block content %}
  <h2>Edit Story</h2>

  <div id="edit-wrapper">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save Changes</button>
      <!-- Add a "Cancel" button to redirect back to the story detail page without saving changes -->
      <a href="{% url 'news:story' story.id %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>

  <div id="delete-wrapper">
  {% comment %} Add delete story functionality {% endcomment %}
    <form method="post" action="{% url 'news:delete_story' story.id %}">
      {% csrf_token %}
      <button type="submit" onclick="return confirm('Are you sure you want to delete this story?')">Delete</button>
    </form>
  </div>

{% endblock %}

she_codes_news/templates/base.html
<!-- templates/base.html -->
{% load static %} <!-- load artefacts from static folder -->

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Yara Fe Tuguinay">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}
        {% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- Content Blocks -->
        {% block content %}
        {% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>

    <!-- Check to see if user accessing page is logged in -->
    {% if request.user.is_authenticated %}
        <a href="{% url 'users:user-profile' user.id %}">{{ user.username }}</a> <!-- Get username if authenticated -->
        <a href="{% url 'news:newStory' %}">Add a New Story</a> <!-- Allow story creation -->
        <a href="{% url 'logout' %}">Logout</a>
    
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Create Account</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}

    <h2>Create Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Account</button>
    </form>

{% endblock %}

she_codes_news/users/templates/users/user-profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        <h2>{{ object.first_name }}'s Profile</h2>
        <div id = "profile-pic">
            <img src="{% static '/users/images/profileicon.png' %}">
        </div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form>  
{% endblock %}